FROM python:3.10.12

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /app

CMD ["gunicorn", "MotoFlow.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]


#STWORZYC KATALOG Z USTAWIENIAMI I Z SETTIGSAMI DLA DEV I PROD
